import type { Carrier, Product, Shipment } from "@repo/shared-types";

export const products: Product[] = [
  {
    sku: "SHOE-BLK-42",
    name: "Black Running Shoes - Size 42",
    category: "Fashion",
    weightKg: 0.8,
    dimensions: { lengthCm: 35, widthCm: 22, heightCm: 12 },
    warehouse: "Los Angeles",
    stockQuantity: 45,
    minStockThreshold: 20,
    unitCostUSD: 52,
    isFragile: false,
    status: "Active",
  },
  {
    sku: "CAM-4K-PRO",
    name: "4K Action Camera",
    category: "Electronics",
    weightKg: 0.45,
    dimensions: { lengthCm: 12, widthCm: 9, heightCm: 8 },
    warehouse: "Zaragoza",
    stockQuantity: 9,
    minStockThreshold: 12,
    unitCostUSD: 148,
    isFragile: true,
    status: "Low stock",
  },
  {
    sku: "SERUM-VITC",
    name: "Vitamin C Serum",
    category: "Cosmetics",
    weightKg: 0.18,
    dimensions: { lengthCm: 11, widthCm: 4, heightCm: 4 },
    warehouse: "Zaragoza",
    stockQuantity: 130,
    minStockThreshold: 35,
    unitCostUSD: 18,
    isFragile: true,
    status: "Active",
  },
];

export const shipments: Shipment[] = [
  {
    id: "SH-2026-1048",
    sku: "SHOE-BLK-42",
    quantity: 2,
    origin: "Los Angeles",
    destination: {
      city: "Austin",
      country: "United States",
      postalCode: "78701",
      distanceKm: 1985,
    },
    priority: "Express",
    declaredValueUSD: 140,
    carrier: null,
    status: "Pending",
    createdAt: new Date("2026-05-21T14:30:00Z"),
  },
  {
    id: "SH-2026-1051",
    sku: "CAM-4K-PRO",
    quantity: 1,
    origin: "Zaragoza",
    destination: {
      city: "Valencia",
      country: "Spain",
      postalCode: "46001",
      distanceKm: 310,
    },
    priority: "Standard",
    declaredValueUSD: 240,
    carrier: null,
    status: "Pending",
    createdAt: new Date("2026-05-22T09:10:00Z"),
  },
  {
    id: "SH-2026-1054",
    sku: "SERUM-VITC",
    quantity: 8,
    origin: "Zaragoza",
    destination: {
      city: "Madrid",
      country: "Spain",
      postalCode: "28001",
      distanceKm: 315,
    },
    priority: "Same-day",
    declaredValueUSD: 224,
    carrier: null,
    status: "Pending",
    createdAt: new Date("2026-05-23T11:45:00Z"),
  },
];

export const carriers: Carrier[] = [
  {
    id: "CAR-UPS",
    name: "UPS",
    operatesIn: ["United States"],
    baseRateUSD: 7.5,
    ratePerKgUSD: 2.4,
    ratePerKmUSD: 0.018,
    avgDeliveryDays: 2,
    onTimeRate: 92,
    maxWeightKg: 30,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express"],
  },
  {
    id: "CAR-FEDEX",
    name: "FedEx",
    operatesIn: ["United States"],
    baseRateUSD: 8.25,
    ratePerKgUSD: 2.1,
    ratePerKmUSD: 0.02,
    avgDeliveryDays: 1.8,
    onTimeRate: 94,
    maxWeightKg: 25,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express", "Same-day"],
  },
  {
    id: "CAR-MRW",
    name: "MRW",
    operatesIn: ["Spain"],
    baseRateUSD: 5.8,
    ratePerKgUSD: 1.6,
    ratePerKmUSD: 0.015,
    avgDeliveryDays: 1.5,
    onTimeRate: 88,
    maxWeightKg: 20,
    handlesFragile: false,
    acceptsPriority: ["Standard", "Express"],
  },
  {
    id: "CAR-SEUR",
    name: "SEUR",
    operatesIn: ["Spain"],
    baseRateUSD: 6.4,
    ratePerKgUSD: 1.7,
    ratePerKmUSD: 0.017,
    avgDeliveryDays: 1.2,
    onTimeRate: 91,
    maxWeightKg: 18,
    handlesFragile: true,
    acceptsPriority: ["Standard", "Express", "Same-day"],
  },
];
