"""Deterministic generator for the TrackFlow 10-year monthly revenue dataset.

Provenance
----------
`sales_prediction.md` instructs that the dataset is "already included" at
`data/raw/trackflow_sales.csv` and says not to generate or simulate it. That file does
not exist in this repository, and no production source can supply it: the operational
database holds roughly two weeks of synthetic inventory movements with no revenue
dimension and effectively no history. Generation was therefore approved by the owner
(OD-10) as an explicit, documented deviation.

This script is the sole authority for that CSV. It is dependency-free (standard library
only) and fully deterministic, so the dataset can be regenerated byte-for-byte and
audited without trusting the committed file.

Specification implemented (from `sales_prediction.md`)
-----------------------------------------------------
- 120 monthly `consolidated` rows, 2016-01 through 2025-12, no gaps.
- Columns: month, revenue_eur, shipments_processed, avg_revenue_per_shipment_eur, market.
- Base annual growth X = 6% with variation Y = 3%; realized annual growth alternates
  between X+Y (9%) and X-Y (3%), always positive.
- Seasonality: November and December +25% to +35%; February -10% to -15%; every other
  month within +/-5%.
- All revenue values positive. Fixed seed (42).

Interpretation recorded explicitly
----------------------------------
Seasonal percentages are expressed **relative to the year's trend monthly average**
(annual trend revenue / 12), which is the natural reading of "relative to the average".
Because the November/December uplift exceeds the February drop, the *realized* annual
mean sits above the trend average, so a peak month measured against the realized mean
reads slightly lower than against the trend. Both figures are reported by
`--report` so no downstream reader has to guess which reference was used.

Business anchoring
------------------
The 2016 trend base is set so realized 2025 revenue lands near 9M EUR, matching the
company profile in `memory-bank/projectbrief.md` ("about 9M EUR in annual revenue").
Revenue per shipment starts near 9.00 EUR and drifts down about 1.2% per year, with a
small additional discount in peak months, which keeps shipment volumes plausible for a
two-warehouse last-mile operator.

Usage
-----
    python scripts/generate_trackflow_sales.py          # write data/raw/trackflow_sales.csv
    python scripts/generate_trackflow_sales.py --report # write and print validation summary
    python scripts/generate_trackflow_sales.py --check  # validate the permanent CSV, write nothing
"""

from __future__ import annotations

import argparse
import csv
import math
import random
from dataclasses import dataclass
from pathlib import Path

SEED = 42
START_YEAR = 2016
END_YEAR = 2025

# Trend base chosen so realized 2025 revenue lands near the 9M EUR company profile.
BASE_ANNUAL_REVENUE_EUR = 5_000_000.0
BASE_GROWTH = 0.06          # X
GROWTH_VARIATION = 0.03     # Y  -> realized growth alternates 9%, 3%, 9%, ...

PEAK_MONTHS = (11, 12)
TROUGH_MONTH = 2
PEAK_MULTIPLIER_RANGE = (1.25, 1.35)
TROUGH_MULTIPLIER_RANGE = (0.85, 0.90)
ORDINARY_MULTIPLIER_RANGE = (0.95, 1.05)

BASE_REVENUE_PER_SHIPMENT_EUR = 9.00
REVENUE_PER_SHIPMENT_ANNUAL_DRIFT = 0.988   # ~1.2% decline per year
PEAK_SHIPMENT_DISCOUNT = 0.97               # volume discount during Black Friday / holiday
REVENUE_PER_SHIPMENT_NOISE_RANGE = (0.98, 1.02)

FIELDNAMES = (
    "month",
    "revenue_eur",
    "shipments_processed",
    "avg_revenue_per_shipment_eur",
    "market",
)
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "data" / "raw" / "trackflow_sales.csv"


class DatasetValidationError(ValueError):
    """Raised when a CSV cannot be parsed into the fixed dataset contract."""


@dataclass(frozen=True)
class MonthlyRow:
    month: str
    revenue_eur: float
    shipments_processed: int
    avg_revenue_per_shipment_eur: float
    market: str = "consolidated"

    def as_dict(self) -> dict[str, object]:
        return {
            "month": self.month,
            "revenue_eur": f"{self.revenue_eur:.2f}",
            "shipments_processed": self.shipments_processed,
            "avg_revenue_per_shipment_eur": f"{self.avg_revenue_per_shipment_eur:.2f}",
            "market": self.market,
        }


def annual_trend_revenue(year: int) -> float:
    """Compound the alternating 9% / 3% growth from the 2016 base."""
    revenue = BASE_ANNUAL_REVENUE_EUR
    for offset in range(year - START_YEAR):
        growth = BASE_GROWTH + GROWTH_VARIATION if offset % 2 == 0 else BASE_GROWTH - GROWTH_VARIATION
        revenue *= 1.0 + growth
    return revenue


def seasonal_multiplier(month: int, rng: random.Random) -> float:
    if month in PEAK_MONTHS:
        return rng.uniform(*PEAK_MULTIPLIER_RANGE)
    if month == TROUGH_MONTH:
        return rng.uniform(*TROUGH_MULTIPLIER_RANGE)
    return rng.uniform(*ORDINARY_MULTIPLIER_RANGE)


def generate_rows() -> list[MonthlyRow]:
    """Build all 120 rows in a fixed draw order so the output is reproducible."""
    rng = random.Random(SEED)
    rows: list[MonthlyRow] = []
    for year in range(START_YEAR, END_YEAR + 1):
        trend_monthly = annual_trend_revenue(year) / 12.0
        rps_year = BASE_REVENUE_PER_SHIPMENT_EUR * (REVENUE_PER_SHIPMENT_ANNUAL_DRIFT ** (year - START_YEAR))
        for month in range(1, 13):
            revenue = round(trend_monthly * seasonal_multiplier(month, rng), 2)
            rps_target = rps_year * rng.uniform(*REVENUE_PER_SHIPMENT_NOISE_RANGE)
            if month in PEAK_MONTHS:
                rps_target *= PEAK_SHIPMENT_DISCOUNT
            shipments = max(1, round(revenue / rps_target))
            # Recompute the average from the two published values so the three numeric
            # columns are internally consistent for any validator that cross-checks them.
            rows.append(
                MonthlyRow(
                    month=f"{year}-{month:02d}-01",
                    revenue_eur=revenue,
                    shipments_processed=shipments,
                    avg_revenue_per_shipment_eur=round(revenue / shipments, 2),
                )
            )
    return rows


def validate(rows: list[MonthlyRow]) -> list[str]:
    """Return a list of specification violations; empty means the dataset conforms."""
    problems: list[str] = []

    expected = [
        f"{year}-{month:02d}-01"
        for year in range(START_YEAR, END_YEAR + 1)
        for month in range(1, 13)
    ]
    month_sequence_valid = [row.month for row in rows] == expected
    if not month_sequence_valid:
        problems.append("month sequence is not a complete, ordered 2016-01..2025-12 series")
    if len(rows) != 120:
        problems.append(f"expected 120 rows, found {len(rows)}")
    if any(row.market != "consolidated" for row in rows):
        problems.append("every row must carry market='consolidated'")
    if any(not math.isfinite(row.revenue_eur) or row.revenue_eur <= 0 for row in rows):
        problems.append("all revenue_eur values must be positive and finite")
    if any(row.shipments_processed <= 0 for row in rows):
        problems.append("all shipments_processed values must be positive")
    if any(
        not math.isfinite(row.avg_revenue_per_shipment_eur)
        or row.avg_revenue_per_shipment_eur <= 0
        for row in rows
    ):
        problems.append("all avg_revenue_per_shipment_eur values must be positive and finite")

    for row in rows:
        if (
            not math.isfinite(row.revenue_eur)
            or row.revenue_eur <= 0
            or row.shipments_processed <= 0
            or not math.isfinite(row.avg_revenue_per_shipment_eur)
            or row.avg_revenue_per_shipment_eur <= 0
        ):
            continue
        implied = round(row.revenue_eur / row.shipments_processed, 2)
        if abs(implied - row.avg_revenue_per_shipment_eur) > 0.005:
            problems.append(f"{row.month}: avg_revenue_per_shipment_eur inconsistent with the other columns")

    if not month_sequence_valid:
        return problems

    for year in range(START_YEAR, END_YEAR + 1):
        year_rows = [row for row in rows if row.month.startswith(str(year))]
        trend_monthly = annual_trend_revenue(year) / 12.0
        for row in year_rows:
            month = int(row.month[5:7])
            ratio = row.revenue_eur / trend_monthly
            if month in PEAK_MONTHS and not 1.25 <= ratio <= 1.35:
                problems.append(f"{row.month}: peak uplift {ratio:.3f} outside 1.25-1.35 of trend average")
            elif month == TROUGH_MONTH and not 0.85 <= ratio <= 0.90:
                problems.append(f"{row.month}: February drop {ratio:.3f} outside 0.85-0.90 of trend average")
            elif month not in PEAK_MONTHS and month != TROUGH_MONTH and not 0.95 <= ratio <= 1.05:
                problems.append(f"{row.month}: ordinary month {ratio:.3f} outside 0.95-1.05 of trend average")

    return problems


def write_csv(rows: list[MonthlyRow], destination: Path) -> None:
    with destination.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        for row in rows:
            writer.writerow(row.as_dict())


def read_csv(source: Path) -> list[MonthlyRow]:
    try:
        with source.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            if reader.fieldnames != list(FIELDNAMES):
                raise DatasetValidationError(
                    f"expected columns {list(FIELDNAMES)}, found {reader.fieldnames}"
                )
            rows: list[MonthlyRow] = []
            for line_number, record in enumerate(reader, start=2):
                if any(record[field] is None or not record[field].strip() for field in FIELDNAMES):
                    raise DatasetValidationError(f"line {line_number}: empty field")
                rows.append(
                    MonthlyRow(
                        month=record["month"],
                        revenue_eur=float(record["revenue_eur"]),
                        shipments_processed=int(record["shipments_processed"]),
                        avg_revenue_per_shipment_eur=float(
                            record["avg_revenue_per_shipment_eur"]
                        ),
                        market=record["market"],
                    )
                )
            return rows
    except (OSError, KeyError, TypeError, ValueError) as exc:
        if isinstance(exc, DatasetValidationError):
            raise
        raise DatasetValidationError(f"cannot read valid TrackFlow sales data: {exc}") from exc


def report(rows: list[MonthlyRow]) -> str:
    lines = ["year   revenue_eur     shipments    growth   feb_vs_trend  nov_vs_trend  dec_vs_trend"]
    previous_total = None
    for year in range(START_YEAR, END_YEAR + 1):
        year_rows = [row for row in rows if row.month.startswith(str(year))]
        total = sum(row.revenue_eur for row in year_rows)
        shipments = sum(row.shipments_processed for row in year_rows)
        trend_monthly = annual_trend_revenue(year) / 12.0
        by_month = {int(row.month[5:7]): row.revenue_eur for row in year_rows}
        growth = "     -" if previous_total is None else f"{(total / previous_total - 1) * 100:+5.1f}%"
        lines.append(
            f"{year}   {total:12,.0f}   {shipments:10,}   {growth}"
            f"        {by_month[2] / trend_monthly:5.3f}         {by_month[11] / trend_monthly:5.3f}"
            f"         {by_month[12] / trend_monthly:5.3f}"
        )
        previous_total = total

    realized_mean = sum(row.revenue_eur for row in rows[-12:]) / 12
    trend_mean = annual_trend_revenue(END_YEAR) / 12
    lines.append("")
    lines.append(f"2025 trend monthly average:    {trend_mean:12,.0f} EUR")
    lines.append(f"2025 realized monthly average: {realized_mean:12,.0f} EUR")
    lines.append(
        "Peak months measured against the realized mean read "
        f"{(rows[-1].revenue_eur / realized_mean - 1) * 100:.1f}% (December), "
        "versus the trend-average figure in the table above."
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--report", action="store_true", help="print a validation and shape summary")
    parser.add_argument("--check", action="store_true", help="validate the existing CSV without writing")
    args = parser.parse_args()

    try:
        rows = read_csv(args.output) if args.check else generate_rows()
    except DatasetValidationError as exc:
        print(f"validation error: {exc}")
        return 1
    problems = validate(rows)

    if not args.check:
        write_csv(rows, args.output)
        print(f"wrote {len(rows)} rows to {args.output}")

    if args.report or args.check:
        print(report(rows))

    if problems:
        print("\nSPEC VIOLATIONS:")
        for problem in problems:
            print(f"  - {problem}")
        return 1
    print("\nvalidation: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
